### PR TITLE
Layout change - Data file view moved to left side

### LINKED ISSUE #420: Odd placement and sizing of controls
Since #413, the controls in the window look a little odd:

image

There are several related issues (#405, #419, #396), but one other problem may be that there are too many controls on the right compared to the left of the window. One tweak that could be made is to move the data file control to the left-hand side.

Another possibility is that the temperature plot is too large.

### PR DESCRIPTION
**Pull request by CWestICL**
GUI layout change to move Data file view from right side to left side.

I think this change makes sense for the layout as it creates a divide between the temperature monitoring views on the right and the config/other sensors on the left.
image

However now that the Data file view is on the left, its width is shortened and the directory/filename fields are a bit stubby. I suggest changing the layout of the Data file view so that these two fields are vertically aligned. I've attempted to do this with the `QGridLayout` but I still need to play around to get the elements aligned properly.
image

Opening in draft to get feedback on this layout change before it's refined.

Closes #420

### CODE REVIEW

**Comment by dc2917** [comment]
I think moving the Data File panel to the left makes sense now that the left-hand side is less busy. If you want to align the components, you can stick each of them in a `QGridLayout` - an example of this is in temperature_monitor_view.py, but actually, most of the panels contain QGridLayouts so there should be a few examples to refer to.

**Review by jamesturner246 — APPROVED** [review]
Looks good and tidy -- agree with Dan.

**Comment by CWestICL** [comment]
This is the best I've been able to align the elements with the `QGridLayout`. Still not perfect, not sure if anyone has some ideas on getting it a bit tidier.
image

**Review by jamesturner246 — APPROVED** [review]
Whilst I'm not super familiar with GUI design, the buttons do fill the area more neatly this time. It's an approval from me, but maybe someone with more QT experience knows differently.

**Comment by CWestICL** [comment]
Ah perfect, that's done it. Looks much cleaner now!
image

**Review by dc2917 — APPROVED** [review]
Yep, looks good, nice one!

**Pull request merged**
